config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  


  
  get '/pages/home', to: 'pages#home'

  resources :users
  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :projects
  resources :bugs
 


 
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(current_user)
    if current_user
    if current_user.role == 'manager'
      
      can :read, User
      can :read, Project
      can :read, Bug
      can :create, Project
      can :edit, Project
      can :update, Project
      can :destroy, Project
    end


    if current_user.role == 'developer'
      
      can :read, User
      can :read, Project
      can :read, Bug
      can :edit, Bug
      can :update, Bug
    end

    
     
    if current_user.role == 'qa'
      
      can :read, User
      can :read, Project
      can :read, Bug
      can :create, Bug
      can :destroy, Bug
    end
  end
    

   

    
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bug.rb
class Bug < ApplicationRecord
    belongs_to :project

    

    belongs_to :bug_creator, class_name: "User", foreign_key: "creator_id"
    belongs_to :bug_assignee, class_name: "User", foreign_key: "assignee_id"


    enum bug_type: [:feature, :bug]
end

app/models/project.rb
class Project < ApplicationRecord
    
    has_many :user_projects
    has_many :users, through: :user_projects

    belongs_to :project_creator, class_name: "User", foreign_key: "creator_id"

    has_many :bugs     

end

app/models/user.rb
class User < ApplicationRecord
      

    has_many :user_projects
    has_many :projects, through: :user_projects

    has_many :created_projects, class_name: "Project", foreign_key: "creator_id"

    has_many :created_bugs, class_name: "Bug", foreign_key: "creator_id"
    has_many :assigned_bugs, class_name: "Bug", foreign_key: "assignee_id"




  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  
  enum role: [:qa, :manager, :developer]
  

  
  
end

app/models/user_project.rb
class UserProject < ApplicationRecord
    belongs_to :user  
    belongs_to :project



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  add_flash_types :info, :error, :success, :alert

    before_action :configure_permitted_parameters, if: :devise_controller?


    rescue_from CanCan::AccessDenied do | exception |
       redirect_to root_url, alert: exception.message
    end
  

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :role])
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
    load_and_authorize_resource



    
    def index
        @b = Bug.all
        @p = Project.all
        @usr = User.all
    end


    def show
        @b = Bug.find(params[:id])
        @p = Project.find(params[:id])
        @usr = User.find(params[:id])
    end

    def new 
        @b = Bug.new
    end 

    def create
        @b = Bug.new(bug_params)
        @b.creator_id = current_user.id
        if @b.save
            flash[:success] = "Bug created successfully"
            redirect_to bug_path(current_user)
    
        else 
            render 'new'
        end  
    end 


    def edit  
        @b = Bug.find(params[:id])
        #if can? 
            #:edit, @p
        #else
            #flash[:alert] = "you are not allowed to edit"
            #redirect_to projects_path(@p)
        #end
    end 

    def update 
        @b = Bug.find(params[:id])
        if @b.update(bug_params)
            flash[:success] = "bug is updated successfully"
            redirect_to bugs_path
        else
            render 'edit', status: :unprocessable_entity
        end
    end

    def destroy
        @b = Bug.find(params[:id])
        @b.destroy
        redirect_to bugs_path
    end


    private
 
    def bug_params
        params.require(:bug).permit(:title, :status, :bug_type, :assignee_id, :project_id)
        
    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home 
    end





end 

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    load_and_authorize_resource


    def index
        @p = Project.all
        @usr = User.all
        
        
    end


    def show
        @p = Project.find(params[:id])
        
        @usr = User.find(params[:id])
        
    end

    def new 
        @p = Project.new
    end 


    def create
        @p = Project.new(project_params)
        @p.creator_id = current_user.id
        
        
        if @p.save
            
            flash[:success] = "project saveed successfully"
            redirect_to project_path(current_user)
    
        else 
            render 'new'
        end  
    end 


    def edit  
        @p = Project.find(params[:id])
        #if can? :edit,@p
        #else
            #flash[:alert] = "you are not allowed to edit"
            #redirect_to projects_path(@p)
        #end
    end 

    def update 
        @p = Project.find(params[:id])
        if @p.update(project_params)
            flash[:success] = "project is updated successfully"
            redirect_to project_path(current_user)
        else
            render 'edit', status: :unprocessable_entity
        end
    end

    def destroy
        @p = Project.find(params[:id])
        @p.destroy
        redirect_to project_path(current_user)
    end


    private
 
    def project_params
        params.require(:project).permit(:projectname, :description, :assignee_id, :role)
        
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    load_and_authorize_resource


    def index
        @q = User.where(role: 'qa')
        @d = User.where(role: 'developer')
        @m = User.where(role: 'manager')
        @usr = User.all
    end


    def show
        @usr = User.find(params[:id])
    end
    
   
    

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bugs/_bug.html.erb
<div class="container">




<table class="table table-striped">
  <tr align="center">
     <th>Bug Name</th>
  </tr>
<% obj.each do |b|%>

  <tr align="center">
     <td><%=b.title%></td>
     <% if current_user.role == 'qa'%>
        <td><%= link_to "Delete bug", bug_path(b), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, :class => "btn btn-outline-danger" %></td>
     <%end%>
     <% if current_user.role == 'developer'%>
     <td><%= link_to "Solve Bug", edit_bug_path(b), :class => "btn btn-outline-primary"%></td>
     <%end%>


  </tr>
  <% end %> 
</table>

    
    
 

</div>

app/views/bugs/_form.html.erb
<div class="container">
<%= bootstrap_form_for(@b, :html => {class: "form-horizontal", role: "form"}) do |f|%>
    
    <div class="form-group col-md-8">
      <p>
         <%= f.text_field :title%>
      </p>

      
      <p>
         <%= f.text_field :status%>
      </p>

      <p>
         <%= f.text_field :bug_type%>
      </p>

      <p>
        <%= f.text_field :assignee_id, data: { numeric: true } %>
      </p>

      <p>
         <%= f.text_field :project_id, data: { numeric: true } %>
      </p>
      
     

      <p>
         <%= f.submit "Submit Bug"%>
      </p>

       <%end%>

       
      
       </div>
</div>

app/views/bugs/edit.html.erb
<%= render 'form'%>

app/views/bugs/index.html.erb
<div class="container">




<table class="table table-striped">
  <tr align="center">
     <th>Bug Name</th>
  </tr>
<% if current_user.role == 'qa'%>
 <% current_user.created_bugs.each do |b|%>

  <tr align="center">
     <td><%=b.title%></td>
     <td><%= link_to "Delete bug", bug_path(b), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, :class => "btn btn-outline-danger" %></td>
  </tr>
  <% end %> 
<%end%>

<% if current_user.role == 'developer'%>
 <% current_user.assigned_bugs.each do |b|%>

  <tr align="center">
     <td><%=b.title%></td>
     <td><%= link_to "Solve Bug", edit_bug_path(b), :class => "btn btn-outline-primary"%></td>
  </tr>
  <% end %> 
<% end %>

<% if current_user.role == 'manager'%>
 <% @b.each do |b|%>

  <tr align="center">
     <td><%=b.title%></td>
     <td><%= link_to "Solve Bug", edit_bug_path(b), :class => "btn btn-outline-primary"%></td>
  </tr>
  <% end %> 
<% end %>   







  



</table>

</div>

app/views/bugs/new.html.erb
<%= render 'form'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>







  <body>
   <%= render 'shared/navigation'%>
   <% if notice %>
     <p class="alert alert-success"><%= notice %></p>
   <% end %>
   <% if alert %>
     <p class="alert alert-danger"><%= alert %></p>
   <% end %>

   
   <% if success %>
     <p class="alert alert-success"><%= success %></p>
   <% end %>

   <% if error %>
     <p class="alert alert-error"><%= error %></p>
   <% end %>

   <% if info %>
     <p class="alert alert-info"><%= info %></p>
   <% end %>

   
   
      <%= yield %>
    
  </body>
</html>

app/views/pages/home.html.erb
<div class ="container">
<div class="text-bg-secondary p-3">

    <% if current_user %>
     <h2><span class="badge rounded-pill bg-dark"><%= current_user.role%></span></h2>
      <h2>Welcome Back <%= current_user.username%></h2>


      
      
      
     
     




      <br>
      <br>
      <% if current_user.role == 'developer'%>
         <h1 align="center"><%= link_to "Check Assigned Projects", projects_path, :class => "btn btn-outline-info"%></h1>
         <h1 align="center"><%= link_to "Check Assigned Bugs", bugs_path, :class => "btn btn-outline-info"%></h1>
      <% end %>
      <% if current_user.role == 'qa'%>
        <h1 align="center"><%= link_to "Check Assigned Projects", projects_path, :class => "btn btn-outline-info"%></h1>
        <h1 align="center"><%= link_to "Check Created Bugs", bugs_path, :class => "btn btn-outline-info"%></h1>
        <h1 align="center"><%= link_to "Create Bug", new_bug_path, :class => "btn btn-outline-primary"%></h1>
      <% end %>
      <% if current_user.role == 'manager'%>
        <h1 align="center"><%= link_to "Check Created Projects", projects_path, :class => "btn btn-outline-info"%></h1>
        <h1 align="center"><%= link_to "Create Project", new_project_path, :class => "btn btn-outline-primary"%></h1>
      <% end %>
      <hr>
      <h4 align="center">OR</h4>
      <nav class="navbar navbar-light bg-light">
       <form class="container-fluid justify-content-start">
       <button class="btn btn-outline-success me-2" type="button"><%= link_to "Log out!", destroy_user_session_path, 'data-turbo-method': :delete, :class => "btn"%></button>
      </form>
      </nav>
      
    <% else %>
      <h1>Welcome to Bug Tracker</h1>
   <nav class="navbar navbar-light bg-light">
    <form class="container-fluid justify-content-start">
      <button class="btn btn-outline-success me-2" type="button"><%= link_to "Sign up!", new_user_registration_path, :class => "btn" %></button>
      <button class="btn btn-sm btn-outline-secondary" type="button"><%= link_to "Log in!!", new_user_session_path, :class => "btn" %></button>
    </form>
   </nav>
    <% end %>
    </div>
</div>

app/views/projects/_form.html.erb
<div class="container">
<%= bootstrap_form_for(@p, :html => {class: "form-horizontal", role: "form"}) do |f|%>
                                        
    <div class="form-group col-md-8">
      <p>
         <%= f.text_field :projectname%>
      </p>

      
      <p>
         <%= f.text_field :description%>
      </p>


      <p>
      <%= f.text_field :assignee_id, data: { numeric: true } %>
      </p>


      <p>
      <%= f.collection_select(:user_projects, User.developer, :id, :username, {:multiple => :multiple}, :prompt => "Please Select a developer") %>
      </p>

      <p>
      <%= f.collection_select(:user_projects, User.qa, :id, :username, :prompt => "Please Select a qa", multiple: true) %>
      </p>
     

      <p>
           <%= f.submit "Submit Project"%>
       </p>

       

       <%end%>

       
      
       </div>
</div>

app/views/projects/_project.html.erb
    

</div>

app/views/projects/edit.html.erb
<%= render 'form'%>

app/views/projects/index.html.erb
<div class="container">
<h2 align="center"><%= current_user.username%>'s Projects</h2>




<table class="table table-striped">
<tr align="center">
     <th>Project Name</th>
     
    
  </tr>
<% if current_user.role == 'manager'%>
<% current_user.created_projects.each do |p|%>

  <tr align="center">
     <td><%= p.projectname%></td>
     <% if current_user.role == 'manager'%>
        <td><%= link_to "Edit Project", edit_project_path(p), :class => "btn btn-outline-primary"%></td>
        <td><%= link_to "Delete Project", project_path(p), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, :class => "btn btn-outline-danger" %></td>
     <%end%>

     
  </tr>
  <% end %> 
<% end %> 


<% if current_user.role == 'qa'%>
<% current_user.projects.each do |p|%>

  <tr align="center">
     <td><%= p.projectname%></td>
     <% if current_user.role == 'manager'%>
        <td><%= link_to "Edit Project", edit_project_path(p), :class => "btn btn-outline-primary"%></td>
        <td><%= link_to "Delete Project", project_path(p), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, :class => "btn btn-outline-danger" %></td>
     <%end%>

     
  </tr>
  <% end %> 
<% end %> 

<% if current_user.role == 'developer'%>
<% current_user.projects.each do |p|%>

  <tr align="center">
     <td><%= p.projectname%></td>
     <% if current_user.role == 'manager'%>
        <td><%= link_to "Edit Project", edit_project_path(p), :class => "btn btn-outline-primary"%></td>
        <td><%= link_to "Delete Project", project_path(p), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, :class => "btn btn-outline-danger" %></td>
     <%end%>

     
  </tr>
  <% end %> 
<% end %> 
</table>


    

</div>

app/views/projects/new.html.erb
<%= render 'form'%>

app/views/users/_user.html.erb
<div class="container">




<table class="table table-striped">
<tr align="center">
     <th>User Name</th>
    
  </tr>
<% obj.each do |u|%>

  <tr align="center">
     <td><%= u.username%></td>
     
  </tr>
  <% end %>  
</table>

app/views/users/show.html.erb
<td><%= link_to p.projectname, bug_path(p), :class => "btn btn-outline-info"%></td>